
project:
  type: website
  output-dir: docs

website:
  title: "R Learning Website"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - text: Learning Modules
        menu:
          - href: "Intrduction to R and RStudio.qmd"
            text: Introduction to R and RStudio

          - href: "Data Types and Data Structures.qmd"
            text: Data Types and Data Structures

          - href: "Data Import and Export.qmd"
            text: Data Import and Export

          - href: "Reshaping Data with tidyr.qmd"
            text: Reshaping Data with tidyr

          - href: "Data Manipulation with dplyr.qmd"
            text: Data Manipulation with dplyr

          - href: "Data Visualization with ggplot2.qmd"
            text: Data Visualization with ggplot2

          - href: "Statistical Modeling in R.qmd"
            text: Statistical Modeling in R

          - href: "Reproducible Reporting with Quarto.qmd"
            text: Reproducible Reporting with Quarto
            
      - href: about.qmd
        text: About      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    