project:
  type: website
  output-dir: docs

website:
  title: "Learning Python"
  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: Introduction to python.qmd
        text: Introduction to python

      - href: Ipython and Jupyter.qmd
        text: Ipython and Jupyter

      - href: Numpy.qmd
        text: Numpy

      - href: Pandas.qmd
        text: Pandas

      - href: Matplotlifb.qmd
        text: Matplotlifb
        
      - href: Statsmodels.qmd
        text: Statsmodels  
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: source

