project:
  type: website
  output-dir: /docs

website:
  title: "Learning R"
  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: vectors.qmd
        text: Introduction to python

      - href: matrices.qmd
        text: Ipython and Jupyter

      - href: dataframes.qmd
        text: Numpy

      - href: algebra.qmd
        text: Pandas

      - href: functions.qmd
        text: Matplotlifb
        
      - href: dataframes.qmd
        text: Statsmodels  
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: source

